#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""CTR-first title pattern bank for Title Engine V3."""

from __future__ import annotations

CTR_TITLE_PATTERNS = {
    "timeline": [
        "{kw}: What Usually Happens in the First 30 Days — and What Gets Hard Later",
        "{kw}: When Results Usually Start and Where People Get Stuck",
        "{kw}: The First Drop Is Not the Hard Part",
        "{kw}: What Changes First, What Slows Down, and What People Miss",
        "{kw}: The Timeline People Expect vs What Usually Happens",
        "{kw}: Why the First Month Tells You More Than the Hype",
        "{kw}: What the Early Results Can and Cannot Tell You",
        "{kw}: The Results Window Most People Misread",
    ],
    "before_buy": [
        "{kw}: What I’d Avoid Before Spending Money in {year}",
        "{kw}: The Red Flags I’d Check Before Buying Anything",
        "{kw}: What To Know Before You Trust the Label",
        "{kw}: What Usually Disappoints People After They Buy",
        "{kw}: The Buying Filter I’d Use Before Picking One",
        "{kw}: What Looks Promising Until You Read the Fine Print",
        "{kw}: What To Compare Before You Spend a Dollar",
        "{kw}: The Claims I’d Ignore First",
    ],
    "hidden_catch": [
        "{kw}: Why It Went Viral and What Usually Fails First",
        "{kw}: The Hidden Catch Behind the Viral Trend",
        "{kw}: What the Trend Gets Right — and Where It Breaks",
        "{kw}: What TikTok Leaves Out Before People Try It",
        "{kw}: The Simple Promise That Starts Falling Apart in Real Life",
        "{kw}: What Sounds Natural Until the Tradeoff Shows Up",
        "{kw}: The Viral Claim People Keep Repeating Without the Hard Part",
        "{kw}: Before You Try It, Here’s the Part People Skip",
    ],
    "reality_check_ctr": [
        "{question}? The Answer Is Less Clean Than TikTok Makes It",
        "{question}? What Usually Fails First",
        "{question}? The Part Most Advice Leaves Out",
        "{question}? What Actually Holds Up After the Hype",
        "{question}? The Useful Answer Is Not the Simple One",
        "{question}? What People Get Wrong Before They Try It",
        "{question}? The Real-World Answer Most Guides Skip",
        "{question}? What Matters More Than the Headline Claim",
    ],
    "looked_into": [
        "I Looked Into {kw} — The Part People Miss",
        "I Compared {kw} Claims — Most Advice Missed the Same Problem",
        "I Checked the {year} {kw} Landscape — What I’d Watch First",
        "{kw}: What Real Reviews Reveal After the Hype",
        "{kw}: What Users Say Works, and What Usually Breaks Down",
        "{kw}: The Result People Want vs the Friction They Get",
        "{kw}: What Looks Strong Until Real Life Starts Testing It",
        "{kw}: The Review Pattern That Matters More Than the Star Rating",
    ],
    "hidden_risk": [
        "{kw}: What Feels Normal Until It Isn’t",
        "{kw}: The Red Flag People Usually Notice Too Late",
        "{kw}: What Can Go Wrong Before the Results Matter",
        "{kw}: The Side Effect Pattern I’d Watch First",
        "{kw}: What People Downplay Until It Disrupts the Routine",
        "{kw}: The Safety Question That Should Come Before the Promise",
        "{kw}: What To Watch Before You Call It Progress",
        "{kw}: The Risk That Gets Buried Under the Success Stories",
    ],
    "money_access": [
        "{kw}: The Cost Question People Usually Ask Too Late",
        "{kw}: What To Check Before Insurance Says No",
        "{kw}: The Access Problem Behind the Search",
        "{kw}: What Can Make the Price Feel Very Different in Real Life",
        "{kw}: What To Ask Before You Pay Out of Pocket",
        "{kw}: The Coverage Trap People Miss Before Starting",
        "{kw}: What Usually Blocks Access After the First Step",
        "{kw}: The Money Part Most Guides Skip",
    ],
    "comparison_decision": [
        "{kw}: Which One Wins, Which One Fails, and Who Should Care",
        "{kw}: The Difference That Actually Changes the Decision",
        "{kw}: Where One Looks Better Until Real Life Gets Involved",
        "{kw}: Which Fits Better Once Cost, Side Effects, and Routine Matter",
        "{kw}: The Tradeoff Most Comparisons Skip",
        "{kw}: What I’d Compare Before Picking One",
        "{kw}: The Head-to-Head Detail That Changes the Answer",
        "{kw}: Why the Better Choice Depends on the Problem You Actually Have",
    ],
    "public_claim": [
        "{kw}: What’s Confirmed, What’s Speculation, and Why People Keep Searching",
        "{kw}: What the Photos Show and What They Don’t Prove",
        "{kw}: The Public Claims People Keep Misreading",
        "{kw}: What Changed, What Is Public, and What Not To Copy",
        "{kw}: The Visible Transformation and the Missing Context",
        "{kw}: What Fans Keep Asking and What Is Actually Known",
        "{kw}: The Claim Everyone Repeats Without Enough Context",
        "{kw}: What the Timeline Shows — and What It Still Can’t Prove",
    ],
    "before_next_dose": [
        "{kw}: What To Check Before Your Next Dose",
        "{kw}: Site Choice, Comfort, and the Mistake People Make",
        "{kw}: Where To Inject, What To Rotate, and What To Avoid",
        "{kw}: The Practical Detail People Usually Ask Too Late",
        "{kw}: What Feels Minor Until It Becomes a Routine Problem",
        "{kw}: The Next-Dose Question Worth Asking First",
        "{kw}: Stomach vs Thigh and the Rotation Problem People Miss",
        "{kw}: What To Know Before You Guess the Injection Site",
    ],
    "practical_filter": [
        "{kw}: What Helps a Little and What Just Sells Hype",
        "{kw}: The Part Most Advice Leaves Out",
        "{kw}: What Works in Real Life and What Only Sounds Healthy",
        "{kw}: The Simple Filter I’d Use Before Trying It",
        "{kw}: What Usually Helps — and What Backfires Quietly",
        "{kw}: The Difference Between Useful and Overhyped",
        "{kw}: What To Keep, What To Skip, and What To Stop Believing",
        "{kw}: The Real-World Test Most Wellness Advice Fails",
    ],
    "hidden_context": [
        "{kw}: The Part People Miss Before They Decide",
        "{kw}: What Sounds Simple Until Real Life Tests It",
        "{kw}: The Detail That Changes How You Should Read the Claim",
        "{kw}: What Most Search Results Get Half Right",
        "{kw}: The Real Question Behind the Search",
        "{kw}: What Looks Clear Until You Compare the Tradeoffs",
        "{kw}: The Practical Answer Most Guides Skip",
        "{kw}: Why the Search Is More Complicated Than It Looks",
    ],
}

CTR_WEAK_PHRASES = [
    "what to track",
    "what to watch",
    "claims that matter",
    "what to compare first",
    "real results, weak spots",
    "evidence",
    "benefits, weak spots",
    "what actually changed",
    "what works, what fails",
]

CTR_STRONG_TOKENS = [
    "first 30 days",
    "what gets hard later",
    "usually fails first",
    "hidden catch",
    "before spending money",
    "what i’d avoid",
    "tiktok",
    "went viral",
    "confirmed",
    "speculation",
    "photos show",
    "don’t prove",
    "what feels normal until it isn’t",
    "red flag",
    "too late",
    "before your next dose",
    "real life",
    "part people miss",
    "fine print",
    "before you try",
    "before you buy",
]
