#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Composable CTR headline fragments for Title Engine V3.3.

This bank keeps the approved CTR style but makes the system scale beyond a
fixed template list. A title can be built from opener + hook + contrast pieces,
which creates many more usable frames without lowering the editorial standard.
"""

from __future__ import annotations

ANGLE_GRAMMAR = {
    "timeline": {
        "lead": [
            "What Usually Changes First",
            "What the First Month Really Shows",
            "When Results Start To Feel Real",
            "What Happens Before the Scale Slows",
            "The Early Signal People Overread",
            "What Starts Fast and What Does Not",
            "The First Signs People Usually Notice",
            "What the First Few Weeks Can Actually Tell You",
        ],
        "contrast": [
            "and What Gets Hard Later",
            "before the Plateau Shows Up",
            "before Maintenance Becomes the Real Test",
            "and Why Early Progress Can Mislead You",
            "before the Routine Stops Feeling New",
            "and Where People Usually Get Stuck",
            "before the Hard Part Starts",
            "and What People Usually Miss Next",
        ],
        "shape": ["colon_dash", "colon_and", "colon_before"],
    },
    "before_buy": {
        "lead": [
            "What I’d Check Before Buying Anything",
            "What I’d Avoid Before Spending Money",
            "The Red Flags I’d Look For First",
            "What To Question Before You Trust the Label",
            "The Buyer’s Test I’d Use First",
            "What People Usually Wish They Checked First",
            "What Makes It Look Better Than It Is",
            "The Label Detail That Should Change Your Decision",
        ],
        "contrast": [
            "before the Price Looks Worth It",
            "before the Fine Print Matters",
            "before the Hype Gets Expensive",
            "before You Add It to Cart",
            "before Reviews Make the Choice for You",
            "before the Best-Seller Badge Wins You Over",
            "before the Marketing Sounds Too Convincing",
            "before You Spend a Dollar",
        ],
        "shape": ["colon_dash", "colon_before", "colon_and"],
    },
    "hidden_catch": {
        "lead": [
            "Why It Went Viral",
            "The Hidden Catch Behind the Trend",
            "What the Trend Gets Right",
            "What TikTok Leaves Out",
            "Why the Claim Feels So Convincing",
            "What People Copy Too Quickly",
            "The Easy Version Everyone Repeats",
            "The Part That Goes Viral First",
        ],
        "contrast": [
            "and What Usually Fails First",
            "before Real Life Tests It",
            "and Where It Starts To Break",
            "before People Try It",
            "and Why That Still Is Not Enough",
            "before the Tradeoff Shows Up",
            "and What It Leaves Out",
            "before the Results Get Tested",
        ],
        "shape": ["colon_dash", "colon_and", "colon_before"],
    },
    "reality_check_ctr": {
        "lead": [
            "The Answer Is Less Clean Than It Looks",
            "The Straight Answer Has a Catch",
            "What Most Quick Answers Get Wrong",
            "The Part That Changes the Whole Answer",
            "What Sounds Right but Needs Context",
            "The Useful Answer Is Not the Simple One",
            "What Actually Matters in Real Life",
            "Why the Simple Answer Can Mislead You",
        ],
        "contrast": [
            "after the Hype",
            "before You Try It",
            "when Real Life Gets Involved",
            "once You Track the Details",
            "before You Trust the Claim",
            "when the Routine Starts",
            "before the Promise Sounds Too Easy",
            "after You Compare the Tradeoffs",
        ],
        "shape": ["question_colon", "question_dash", "question_direct"],
    },
    "looked_into": {
        "lead": [
            "I Looked Past the Hype",
            "I Checked the Review Pattern",
            "I Compared the Claims",
            "I Looked at What Users Actually Repeat",
            "I Checked the Complaints First",
            "I Looked Beyond the Best Reviews",
            "I Compared the Promise With the Friction",
            "I Looked for the Signal Behind the Stories",
        ],
        "contrast": [
            "and the Same Problem Kept Showing Up",
            "and the Weak Spot Was Easy To Miss",
            "and the Praise Was Not the Most Useful Part",
            "and the Real-World Pattern Was More Useful",
            "before the Big Claims Made Sense",
            "and the Friction Changed the Story",
            "and the Result Was Less Simple Than the Reviews",
            "and One Detail Kept Coming Back",
        ],
        "shape": ["editorial_dash", "colon_dash", "colon_and"],
    },
    "hidden_risk": {
        "lead": [
            "What Feels Normal Until It Is Not",
            "The Red Flag People Notice Too Late",
            "What Can Go Wrong Before Results Matter",
            "The Side Effect Pattern To Watch First",
            "What People Downplay Too Quickly",
            "The Safety Question That Should Come First",
            "What Can Feel Like Progress at First",
            "The Risk Buried Under the Success Stories",
        ],
        "contrast": [
            "before You Call It Progress",
            "before the Routine Gets Disrupted",
            "before It Becomes a Bigger Problem",
            "before You Explain It Away",
            "before the Promise Matters",
            "when the Routine Starts Changing",
            "before It Feels Serious",
            "before the Results Distract You",
        ],
        "shape": ["colon_dash", "colon_before", "colon_and"],
    },
    "money_access": {
        "lead": [
            "The Cost Question People Ask Too Late",
            "What To Check Before Insurance Says No",
            "The Access Problem Behind the Search",
            "What To Ask Before You Pay Out of Pocket",
            "The Coverage Detail That Changes the Plan",
            "Why Getting It Can Be Harder Than Wanting It",
            "What Can Turn a Good Option Into an Expensive One",
            "The Approval Step People Underestimate",
        ],
        "contrast": [
            "before the First Bill Shows Up",
            "before You Start the Process",
            "when Coverage Rules Get Involved",
            "before the Price Feels Different",
            "before You Assume It Is Covered",
            "after the First Step",
            "before Access Becomes the Real Problem",
            "before the Plan Gets Expensive",
        ],
        "shape": ["colon_dash", "colon_before", "colon_and"],
    },
    "comparison_decision": {
        "lead": [
            "Which One Looks Better on Paper",
            "The Difference That Changes the Decision",
            "What To Compare Before Picking One",
            "Where One Wins and the Other Gets Complicated",
            "The Tradeoff Most Comparisons Skip",
            "Which Choice Fits Better in Real Life",
            "What Matters More Than the Popular Answer",
            "The Head-to-Head Detail That Changes the Answer",
        ],
        "contrast": [
            "once Cost and Side Effects Matter",
            "before Reviews Decide for You",
            "when the Routine Gets Real",
            "before the Stronger Claim Wins",
            "after You Compare the Downsides",
            "when the Tradeoff Becomes Personal",
            "before You Trust the Easy Winner",
            "once Real Life Gets Involved",
        ],
        "shape": ["colon_dash", "colon_before", "colon_and"],
    },
    "public_claim": {
        "lead": [
            "What Is Confirmed and What Is Speculation",
            "What the Photos Show and Do Not Prove",
            "The Public Claims People Keep Misreading",
            "What Changed Publicly and What Remains Private",
            "The Visible Change and the Missing Context",
            "What Fans Keep Asking",
            "The Claim Everyone Repeats Without Enough Context",
            "The Public Timeline Without the Guesswork",
        ],
        "contrast": [
            "and Why People Keep Searching",
            "before the Story Gets Overstated",
            "when the Internet Fills in the Gaps",
            "before You Copy the Narrative",
            "and What Not To Assume",
            "before the Timeline Gets Misread",
            "when Public Details Turn Into Bigger Claims",
            "and What Is Actually Known",
        ],
        "shape": ["colon_dash", "colon_and", "colon_before"],
    },
    "before_next_dose": {
        "lead": [
            "What To Check Before Your Next Dose",
            "Where To Inject and What To Rotate",
            "The Site Choice People Ask About Too Late",
            "Why the Injection Spot Should Not Be Random",
            "The Comfort Detail People Usually Ignore",
            "What To Ask Before You Change the Spot",
            "The Small Site Detail That Changes the Routine",
            "What To Know Before You Guess the Injection Site",
        ],
        "contrast": [
            "before the Routine Gets Repetitive",
            "before You Repeat the Same Mistake",
            "when Comfort Starts To Matter",
            "before Site Rotation Gets Confusing",
            "before the Next Shot",
            "when the Routine Feels Easy",
            "before Irritation Becomes a Pattern",
            "before You Make It a Habit",
        ],
        "shape": ["colon_dash", "colon_before", "colon_and"],
    },
    "practical_filter": {
        "lead": [
            "What Helps a Little and What Just Sells Hype",
            "The Simple Filter I’d Use Before Trying It",
            "What Works in Real Life and What Only Sounds Healthy",
            "What Usually Helps and What Backfires Quietly",
            "The Difference Between Useful and Overhyped",
            "What Actually Fits a Weight-Loss Routine",
            "The Everyday Test That Cuts Through the Hype",
            "What To Keep, Limit, and Stop Believing",
        ],
        "contrast": [
            "before You Add It to the Routine",
            "when the Wellness Claim Sounds Too Easy",
            "before the Healthy Label Misleads You",
            "after Real Life Tests It",
            "before You Treat It Like a Shortcut",
            "when the Rest of the Routine Does Not Support It",
            "before Generic Advice Wastes Your Time",
            "once the Details Start Matter",
        ],
        "shape": ["colon_dash", "colon_before", "colon_and"],
    },
    "hidden_context": {
        "lead": [
            "The Part People Miss Before They Decide",
            "What Sounds Simple Until Real Life Tests It",
            "The Detail That Changes the Whole Answer",
            "What Most Search Results Get Half Right",
            "The Real Question Behind the Search",
            "What Looks Clear Until You Compare Tradeoffs",
            "The Missing Piece Behind the Quick Answer",
            "What the Search Phrase Does Not Say Out Loud",
        ],
        "contrast": [
            "before You Act on the Advice",
            "when the Simple Claim Gets Complicated",
            "before the Answer Starts To Matter",
            "once You Compare the Friction",
            "before Generic Advice Sounds Useful",
            "when One Question Is Really Three",
            "before You Trust the Obvious Answer",
            "after the First Try",
        ],
        "shape": ["colon_dash", "colon_before", "colon_and"],
    },
}
