#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""CTR-first title pattern bank for Title Engine V3.

V3.2 expands each CTR angle with more headline frames so the same topic cluster
has enough alternatives and does not keep reusing the same hook.
"""

from __future__ import annotations

CTR_TITLE_PATTERNS = {
    "timeline": [
        "{kw}: What Usually Happens in the First 30 Days — and What Gets Hard Later",
        "{kw}: When Results Usually Start and Where People Get Stuck",
        "{kw}: The First Drop Is Not the Hard Part",
        "{kw}: What Changes First, What Slows Down, and What People Miss",
        "{kw}: The Timeline People Expect vs What Usually Happens",
        "{kw}: Why the First Month Tells You More Than the Hype",
        "{kw}: What the Early Results Can and Cannot Tell You",
        "{kw}: The Results Window Most People Misread",
        "{kw}: The First Signs People Notice Before the Plateau",
        "{kw}: What Starts Fast, What Slows Down, and Why It Matters",
        "{kw}: The Week-by-Week Expectation Most People Get Wrong",
        "{kw}: What the First Month Reveals Before the Scale Stalls",
        "{kw}: Why Early Progress Can Be the Least Useful Signal",
        "{kw}: The Timeline That Sounds Simple Until Real Life Starts",
        "{kw}: What Happens Early and What Usually Decides Long-Term Results",
        "{kw}: The Result Window People Overread Too Soon",
        "{kw}: What To Expect Before the Routine Stops Feeling New",
        "{kw}: The Early Change, the Slowdown, and the Real Test",
    ],
    "before_buy": [
        "{kw}: What I’d Avoid Before Spending Money in {year}",
        "{kw}: The Red Flags I’d Check Before Buying Anything",
        "{kw}: What To Know Before You Trust the Label",
        "{kw}: What Usually Disappoints People After They Buy",
        "{kw}: The Buying Filter I’d Use Before Picking One",
        "{kw}: What Looks Promising Until You Read the Fine Print",
        "{kw}: What To Compare Before You Spend a Dollar",
        "{kw}: The Claims I’d Ignore First",
        "{kw}: What I’d Check Before Adding It to Cart",
        "{kw}: The Expensive Mistake I’d Try To Avoid First",
        "{kw}: What Makes a Product Look Better Than It Is",
        "{kw}: The Label Detail That Should Change Your Decision",
        "{kw}: What To Question Before the Price Looks Worth It",
        "{kw}: Why the Best-Seller Badge Is Not Enough",
        "{kw}: What People Usually Wish They Checked First",
        "{kw}: The Purchase Test I’d Use Before Trusting the Hype",
        "{kw}: What Looks Like Value Until You Compare the Tradeoff",
        "{kw}: The Buyer’s Shortcut That Usually Backfires",
    ],
    "hidden_catch": [
        "{kw}: Why It Went Viral and What Usually Fails First",
        "{kw}: The Hidden Catch Behind the Viral Trend",
        "{kw}: What the Trend Gets Right — and Where It Breaks",
        "{kw}: What TikTok Leaves Out Before People Try It",
        "{kw}: The Simple Promise That Starts Falling Apart in Real Life",
        "{kw}: What Sounds Natural Until the Tradeoff Shows Up",
        "{kw}: The Viral Claim People Keep Repeating Without the Hard Part",
        "{kw}: Before You Try It, Here’s the Part People Skip",
        "{kw}: The Trend Looks Simple Until the Routine Starts",
        "{kw}: What Makes the Claim Feel True — and Why That Is Not Enough",
        "{kw}: The Part That Goes Viral Before the Results Get Tested",
        "{kw}: Why the Recipe Sounds Better Than the Follow-Through",
        "{kw}: The Wellness Shortcut That Still Needs a Reality Check",
        "{kw}: What People Copy Before They Understand the Tradeoff",
        "{kw}: The Small Detail That Changes the Whole Trend",
        "{kw}: Why the Viral Promise Feels So Convincing",
        "{kw}: What the Easy Version Leaves Out",
        "{kw}: The Hype Is Simple; the Real-Life Test Is Not",
    ],
    "reality_check_ctr": [
        "{question}? The Answer Is Less Clean Than TikTok Makes It",
        "{question}? What Usually Fails First",
        "{question}? The Part Most Advice Leaves Out",
        "{question}? What Actually Holds Up After the Hype",
        "{question}? The Useful Answer Is Not the Simple One",
        "{question}? What People Get Wrong Before They Try It",
        "{question}? The Real-World Answer Most Guides Skip",
        "{question}? What Matters More Than the Headline Claim",
        "{question}? The Answer Depends on the Part People Skip",
        "{question}? What Looks True Until You Track the Details",
        "{question}? The Straight Answer Has a Catch",
        "{question}? What Most Quick Answers Get Wrong",
        "{question}? The Part That Changes the Whole Decision",
        "{question}? What Sounds Right but Usually Needs Context",
        "{question}? The Real Answer Is More Practical Than Viral",
        "{question}? What To Believe Before You Try It",
        "{question}? Why the Simple Answer Can Mislead You",
        "{question}? What Actually Matters in Real Life",
    ],
    "looked_into": [
        "I Looked Into {kw} — The Part People Miss",
        "I Compared {kw} Claims — Most Advice Missed the Same Problem",
        "I Checked the {year} {kw} Landscape — What I’d Watch First",
        "{kw}: What Real Reviews Reveal After the Hype",
        "{kw}: What Users Say Works, and What Usually Breaks Down",
        "{kw}: The Result People Want vs the Friction They Get",
        "{kw}: What Looks Strong Until Real Life Starts Testing It",
        "{kw}: The Review Pattern That Matters More Than the Star Rating",
        "I Looked at {kw} Reviews — The Complaints Were More Useful Than the Praise",
        "{kw}: What the Success Stories Make Too Easy To Believe",
        "I Checked {kw} Results — The Pattern Was Not the One I Expected",
        "{kw}: What People Praise First and Question Later",
        "{kw}: The Review Signal I’d Trust Before the Big Claims",
        "I Compared the Claims Around {kw} — Here’s What Kept Showing Up",
        "{kw}: What Real-World Feedback Keeps Repeating",
        "{kw}: The Difference Between a Good Story and a Useful Signal",
        "I Looked Past the Best Reviews for {kw} — That’s Where It Got Interesting",
        "{kw}: What the Most Excited Reviews Still Don’t Answer",
    ],
    "hidden_risk": [
        "{kw}: What Feels Normal Until It Isn’t",
        "{kw}: The Red Flag People Usually Notice Too Late",
        "{kw}: What Can Go Wrong Before the Results Matter",
        "{kw}: The Side Effect Pattern I’d Watch First",
        "{kw}: What People Downplay Until It Disrupts the Routine",
        "{kw}: The Safety Question That Should Come Before the Promise",
        "{kw}: What To Watch Before You Call It Progress",
        "{kw}: The Risk That Gets Buried Under the Success Stories",
        "{kw}: The Symptom People Explain Away Too Quickly",
        "{kw}: What Feels Minor Until It Changes the Routine",
        "{kw}: The Warning Sign That Deserves a Second Look",
        "{kw}: What People Usually Ask After Something Feels Off",
        "{kw}: The Safety Detail That Should Not Be an Afterthought",
        "{kw}: Why the Result Is Not the Only Thing To Watch",
        "{kw}: What Can Feel Like Progress Until It Becomes a Problem",
        "{kw}: The Risk Question Most Guides Put Too Low",
        "{kw}: What I’d Watch Before Calling It Normal",
        "{kw}: The Side-Effect Clue People Often Miss",
    ],
    "money_access": [
        "{kw}: The Cost Question People Usually Ask Too Late",
        "{kw}: What To Check Before Insurance Says No",
        "{kw}: The Access Problem Behind the Search",
        "{kw}: What Can Make the Price Feel Very Different in Real Life",
        "{kw}: What To Ask Before You Pay Out of Pocket",
        "{kw}: The Coverage Trap People Miss Before Starting",
        "{kw}: What Usually Blocks Access After the First Step",
        "{kw}: The Money Part Most Guides Skip",
        "{kw}: Why the Price Is Only One Part of the Problem",
        "{kw}: What To Know Before the First Bill Shows Up",
        "{kw}: The Approval Step People Often Underestimate",
        "{kw}: What Makes Access Easier for Some People and Harder for Others",
        "{kw}: The Question To Ask Before You Assume It’s Covered",
        "{kw}: What Can Turn a Good Option Into an Expensive One",
        "{kw}: The Cost Reality Behind the Search",
        "{kw}: What To Check Before You Start the Process",
        "{kw}: The Coverage Detail That Can Change the Whole Plan",
        "{kw}: Why Getting It Is Often Harder Than Wanting It",
    ],
    "comparison_decision": [
        "{kw}: Which One Wins, Which One Fails, and Who Should Care",
        "{kw}: The Difference That Actually Changes the Decision",
        "{kw}: Where One Looks Better Until Real Life Gets Involved",
        "{kw}: Which Fits Better Once Cost, Side Effects, and Routine Matter",
        "{kw}: The Tradeoff Most Comparisons Skip",
        "{kw}: What I’d Compare Before Picking One",
        "{kw}: The Head-to-Head Detail That Changes the Answer",
        "{kw}: Why the Better Choice Depends on the Problem You Actually Have",
        "{kw}: The Comparison That Looks Simple Until You Add Real Life",
        "{kw}: What Changes When You Compare the Downsides First",
        "{kw}: Which Looks Better on Paper and Which Fits Better in Practice",
        "{kw}: The Decision Point Most Side-by-Side Guides Miss",
        "{kw}: What Matters More Than Which One Sounds Stronger",
        "{kw}: The Choice That Depends on the Tradeoff You Can Live With",
        "{kw}: Where the Popular Answer May Not Be the Right One",
        "{kw}: The Practical Difference Behind the Better Headline",
        "{kw}: What To Compare Before You Let Reviews Decide",
        "{kw}: The Real-Life Filter That Changes the Winner",
    ],
    "public_claim": [
        "{kw}: What’s Confirmed, What’s Speculation, and Why People Keep Searching",
        "{kw}: What the Photos Show and What They Don’t Prove",
        "{kw}: The Public Claims People Keep Misreading",
        "{kw}: What Changed, What Is Public, and What Not To Copy",
        "{kw}: The Visible Transformation and the Missing Context",
        "{kw}: What Fans Keep Asking and What Is Actually Known",
        "{kw}: The Claim Everyone Repeats Without Enough Context",
        "{kw}: What the Timeline Shows — and What It Still Can’t Prove",
        "{kw}: Why the Public Story Keeps Getting Repeated",
        "{kw}: What Is Known, What Is Guessed, and What Gets Overstated",
        "{kw}: The Detail People Keep Turning Into a Bigger Claim",
        "{kw}: What the Before-and-After Talk Leaves Unanswered",
        "{kw}: Why the Transformation Story Needs Context",
        "{kw}: What Changed Publicly and What Remains Private",
        "{kw}: The Part of the Story People Keep Filling In Themselves",
        "{kw}: What the Internet Says vs What Is Actually Clear",
        "{kw}: Why People Search It and What They Should Not Assume",
        "{kw}: The Public Timeline Without the Guesswork",
    ],
    "before_next_dose": [
        "{kw}: What To Check Before Your Next Dose",
        "{kw}: Site Choice, Comfort, and the Mistake People Make",
        "{kw}: Where To Inject, What To Rotate, and What To Avoid",
        "{kw}: The Practical Detail People Usually Ask Too Late",
        "{kw}: What Feels Minor Until It Becomes a Routine Problem",
        "{kw}: The Next-Dose Question Worth Asking First",
        "{kw}: Stomach vs Thigh and the Rotation Problem People Miss",
        "{kw}: What To Know Before You Guess the Injection Site",
        "{kw}: The Small Injection Detail That Can Change the Routine",
        "{kw}: What People Usually Learn After a Few Doses",
        "{kw}: Why Site Rotation Matters More Than It Sounds",
        "{kw}: What To Ask Before You Change the Spot",
        "{kw}: The Comfort Question People Often Ignore",
        "{kw}: What Can Make the Next Dose Feel Different",
        "{kw}: The Practical Site Check Before You Inject Again",
        "{kw}: Why the Injection Spot Should Not Be Random",
        "{kw}: What To Watch When the Routine Starts Feeling Easy",
        "{kw}: The Simple Step That Prevents Repeating the Same Mistake",
    ],
    "practical_filter": [
        "{kw}: What Helps a Little and What Just Sells Hype",
        "{kw}: The Part Most Advice Leaves Out",
        "{kw}: What Works in Real Life and What Only Sounds Healthy",
        "{kw}: The Simple Filter I’d Use Before Trying It",
        "{kw}: What Usually Helps — and What Backfires Quietly",
        "{kw}: The Difference Between Useful and Overhyped",
        "{kw}: What To Keep, What To Skip, and What To Stop Believing",
        "{kw}: The Real-World Test Most Wellness Advice Fails",
        "{kw}: What Sounds Healthy but Still Needs a Plan",
        "{kw}: The Practical Way To Tell If It Belongs in Your Routine",
        "{kw}: What Helps Enough To Matter and What Just Sounds Good",
        "{kw}: The Everyday Test That Cuts Through the Hype",
        "{kw}: What To Use, What To Limit, and What To Ignore",
        "{kw}: The Part That Matters More Than the Wellness Claim",
        "{kw}: What Works Only If the Rest of the Routine Supports It",
        "{kw}: The Common Advice That Needs a Reality Check",
        "{kw}: What Actually Fits a Weight-Loss Routine",
        "{kw}: The Useful Version vs the Overhyped Version",
    ],
    "hidden_context": [
        "{kw}: The Part People Miss Before They Decide",
        "{kw}: What Sounds Simple Until Real Life Tests It",
        "{kw}: The Detail That Changes How You Should Read the Claim",
        "{kw}: What Most Search Results Get Half Right",
        "{kw}: The Real Question Behind the Search",
        "{kw}: What Looks Clear Until You Compare the Tradeoffs",
        "{kw}: The Practical Answer Most Guides Skip",
        "{kw}: Why the Search Is More Complicated Than It Looks",
        "{kw}: The Context That Changes the Whole Answer",
        "{kw}: What People Usually Learn After the First Try",
        "{kw}: The Part That Turns a Simple Claim Into a Real Decision",
        "{kw}: What the Search Phrase Doesn’t Say Out Loud",
        "{kw}: The Missing Piece Behind the Quick Answer",
        "{kw}: Why the Obvious Answer Is Not Always Useful",
        "{kw}: What To Understand Before the Advice Makes Sense",
        "{kw}: The Real-Life Friction Behind the Search",
        "{kw}: What Looks Like One Question but Is Really Three",
        "{kw}: The Detail That Separates Useful Advice From Generic Advice",
    ],
}

CTR_WEAK_PHRASES = [
    "what to track",
    "what to watch",
    "claims that matter",
    "what to compare first",
    "real results, weak spots",
    "evidence",
    "benefits, weak spots",
    "what actually changed",
    "what works, what fails",
]

CTR_STRONG_TOKENS = [
    "first 30 days",
    "what gets hard later",
    "usually fails first",
    "hidden catch",
    "before spending money",
    "what i’d avoid",
    "what i'd avoid",
    "tiktok",
    "went viral",
    "confirmed",
    "speculation",
    "photos show",
    "don’t prove",
    "don't prove",
    "what feels normal until it isn’t",
    "what feels normal until it isn't",
    "red flag",
    "too late",
    "before your next dose",
    "real life",
    "part people miss",
    "fine print",
    "before you try",
    "before you buy",
    "first month",
    "plateau",
    "routine",
    "tradeoff",
    "guesswork",
    "real-world",
    "overhyped",
    "viral promise",
]
