#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Locked viral article controller for local AnQiCMS generation.

The previous segmented Gemini writer could drift into report-style prose,
unsupported medical claims, wrong modality examples, and generic headings.
This controller keeps Gemini for upstream planning when available, but the final
article body is generated by a deterministic local decision-article writer so the
output shape stays stable for batch production.
"""

from __future__ import annotations

import argparse
from datetime import datetime
import json
from pathlib import Path
import re

from pipeline_controller import PipelineController, PipelineResult, ProgressCallback
from preview_renderer import render_preview_html
from publish_articles import load_article


class EditorialPipelineController(PipelineController):
    """PipelineController variant with locked high-conversion article structure."""

    MEDICATION_TOKENS = (
        "mounjaro",
        "tirzepatide",
        "ozempic",
        "semaglutide",
        "wegovy",
        "zbound",
        "glp-1",
        "glp 1",
        "metformin",
        "weight loss drug",
        "weight loss medication",
        "prescription weight loss",
    )
    CBD_TOKENS = ("cbd", "cannabidiol", "hemp", "gummies", "gummy", "tincture")
    BLOOD_TOKENS = (
        "blood",
        "glucose",
        "a1c",
        "cholesterol",
        "triglycerides",
        "insulin",
        "blood pressure",
        "blood sugar",
        "bp",
    )

    def run_stage1_1(self, keyword: str, progress: ProgressCallback | None = None) -> tuple[dict, Path]:
        try:
            return super().run_stage1_1(keyword, progress)
        except RuntimeError as error:
            if "Stage 1-1" not in str(error):
                raise
            if progress:
                progress("Pending", 12, "Stage 1-1 Gemini failed; using local fallback expansion")
            slug = self._slugify(keyword)
            payload = self._build_stage1_1_fallback(keyword)
            path = self.output_root / f"ui_{slug}.stage1_1.json"
            path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
            return payload, path

    def run_stage1_2(
        self,
        keyword: str,
        stage1_1: dict,
        category_id: int | None = None,
        keyword_id: int | None = None,
        progress: ProgressCallback | None = None,
    ) -> tuple[dict, Path]:
        try:
            return super().run_stage1_2(keyword, stage1_1, category_id, keyword_id, progress)
        except RuntimeError as error:
            if "Stage 1-2" not in str(error):
                raise
            if progress:
                progress("Drafting", 30, "Stage 1-2 Gemini failed; using local fallback outline")
            slug = self._slugify(keyword)
            payload = self._build_stage1_2_fallback(keyword, category_id, keyword_id)
            path = self.output_root / f"ui_{slug}.stage1_2.json"
            path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
            return payload, path

    def build_markdown_from_plan(
        self,
        keyword: str,
        stage1_2: dict,
        category_id: int | None = None,
        keyword_id: int | None = None,
        style: str | None = None,
        progress: ProgressCallback | None = None,
    ) -> Path:
        if progress:
            progress("Fact_Checking", 45, "Rendering locked viral decision article")
        slug = self._slugify(keyword)
        markdown_path = self.output_root / f"ui_{slug}.md"
        draft_markdown_path = self.output_root / f"ui_{slug}.draft.md"
        category_value = self._normalize_category_id(category_id)
        title = self._viral_title(keyword)
        description = self._truncate_description(self._viral_description(keyword))
        body = self._build_locked_viral_body(keyword)

        draft_content = self._compose_markdown_document(
            keyword,
            title,
            description,
            category_value,
            keyword_id,
            body,
        )
        draft_markdown_path.write_text(draft_content, encoding="utf-8")
        if progress:
            progress("Fact_Checking", 60, f"Saved locked draft markdown: {draft_markdown_path.name}")

        final_content = self._compose_markdown_document(
            keyword,
            title,
            description,
            category_value,
            keyword_id,
            body,
        )
        markdown_path.write_text(final_content, encoding="utf-8")
        load_article(markdown_path)
        if progress:
            progress("SEO_Optimizing", 70, f"Rendered final markdown: {markdown_path.name}")
        return markdown_path

    def _build_stage1_1_fallback(self, keyword: str) -> dict:
        lane = self._lane(keyword)
        return {
            "sq": keyword,
            "language": "English",
            "tm": "false",
            "ymyl_level": True,
            "lane": lane,
            "qs": [
                {
                    "q": keyword,
                    "i": self._intent_line(keyword),
                    "tm": "false",
                    "ymyl_level": True,
                }
            ],
            "fallback": True,
        }

    def _build_stage1_2_fallback(self, keyword: str, category_id: int | None, keyword_id: int | None) -> dict:
        node = {
            "t": self._viral_title(keyword),
            "mty": "Semantic",
            "cs": {"ty": "Editorial Desk", "ac": "US", "ar": "", "al": ""},
            "category_id": self._normalize_category_id(category_id),
            "cr": {
                "tl": "Locked viral decision article with real-life friction, case pattern, comparison table, action guide, and FAQ.",
                "s": self._viral_description(keyword),
                "wc": 2200,
                "st": self._viral_headings(keyword),
                "kp": self._viral_key_points(keyword),
                "af": "Answer first. Show the real friction. Avoid report voice and unsupported medical claims.",
                "gfm": {"lsr": True},
                "author_bio": self._author_bio(keyword),
                "personal_story": self._opening_story(keyword),
            },
        }
        if keyword_id is not None:
            node["keyword_id"] = keyword_id
        return {"dsq": [{"q": keyword, "i": self._intent_line(keyword), "mt": [node]}], "fallback": True}

    def _lane(self, keyword: str) -> str:
        lowered = keyword.lower()
        if any(token in lowered for token in self.MEDICATION_TOKENS):
            return "medication"
        if any(token in lowered for token in self.CBD_TOKENS):
            return "cbd"
        if any(token in lowered for token in self.BLOOD_TOKENS):
            return "blood"
        return "weight_loss"

    def _subject(self, keyword: str) -> str:
        subject = self._heading_subject(keyword)
        subject = re.sub(r"\s+", " ", subject).strip(" -?") or keyword.strip()
        return subject

    def _title_subject(self, keyword: str) -> str:
        subject = self._subject(keyword)
        minor = {"a", "an", "and", "as", "at", "by", "for", "in", "is", "of", "on", "or", "the", "to", "vs", "with"}
        words: list[str] = []
        for index, word in enumerate(subject.lower().split()):
            if index > 0 and word in minor:
                words.append(word)
            else:
                words.append(word[:1].upper() + word[1:])
        return " ".join(words)

    def _viral_title(self, keyword: str) -> str:
        lane = self._lane(keyword)
        subject = self._title_subject(keyword)
        lowered = keyword.lower()
        if lane == "medication":
            if "metformin" in lowered:
                return "Metformin For Weight Loss Sounds Simple Until The Second Month Gets Messy"
            if "mounjaro" in lowered or "tirzepatide" in lowered:
                return "Mounjaro Weight Loss Looks Powerful Until The Real-Life Friction Shows Up"
            if "ozempic" in lowered or "semaglutide" in lowered:
                return f"{subject} Looks Promising Until The Maintenance Question Shows Up"
            return f"{subject} Sounds Promising Until The Real-Life Tradeoff Shows Up"
        if lane == "cbd":
            if "sleep" in lowered:
                return f"{subject} Sound Easy Until The Morning After Tells The Truth"
            return f"{subject} Sounds Helpful Until You Track The Tradeoff Closely"
        if lane == "blood":
            if "after eating" in lowered or "blood sugar" in lowered:
                return f"{subject} Looks Random Until You Track This Pattern"
            if "cholesterol" in lowered:
                return f"{subject} Is Easy To Ignore Until The Pattern Gets Serious"
            return f"{subject} Looks Small Until The Pattern Starts Repeating"
        return f"{subject} Sounds Easy Until Real Life Starts Testing It"

    def _viral_description(self, keyword: str) -> str:
        lane = self._lane(keyword)
        subject = self._subject(keyword)
        if lane == "medication":
            return f"A real-world decision guide to {subject}, including fit, side effects, access, cost, refill friction, and what to ask before choosing it."
        if lane == "cbd":
            return f"A practical look at {subject}, including expectations, next-day effects, safety questions, product quality, and when to be cautious."
        if lane == "blood":
            return f"A practical guide to {subject}, including patterns to track, what gets missed, and when to discuss the result with a qualified professional."
        return f"A real-world look at {subject}, including what works, what disappoints people, and what to check before committing."

    def _intent_line(self, keyword: str) -> str:
        lane = self._lane(keyword)
        subject = self._subject(keyword)
        if lane == "medication":
            return f"The searcher wants to know whether {subject} is worth considering in real life, including side effects, access, cost, and fit."
        if lane == "cbd":
            return f"The searcher wants to know whether {subject} is actually useful, safe, and worth the tradeoff."
        if lane == "blood":
            return f"The searcher wants to understand what {subject} may mean and what pattern deserves attention."
        return f"The searcher wants a practical answer about {subject}, not a generic explainer."

    def _viral_key_points(self, keyword: str) -> list[str]:
        lane = self._lane(keyword)
        if lane == "medication":
            return [
                "The result is only useful if the medication fits the person's medical context and daily life.",
                "The first month is not the real test; access, side effects, refills, and maintenance reveal the true friction.",
                "A qualified clinician should guide medication decisions, especially with other conditions or prescriptions.",
            ]
        if lane == "cbd":
            return [
                "The useful question is not whether CBD sounds relaxing, but whether the effect is noticeable, safe, and repeatable.",
                "Product quality, dose consistency, drug interactions, next-day grogginess, and legal context change the decision.",
                "A realistic article should not overpromise sleep, pain, or anxiety outcomes.",
            ]
        if lane == "blood":
            return [
                "The pattern matters more than one isolated reading or vague symptom.",
                "Timing, repeat triggers, other symptoms, and medical history change the meaning.",
                "The safest article helps the reader track better and know when to seek professional input.",
            ]
        return [
            "The promise has to be judged against real-life friction.",
            "Early progress is less important than consistency after the novelty fades.",
            "The reader needs a decision checklist, not just encouragement.",
        ]

    def _viral_headings(self, keyword: str) -> list[str]:
        lane = self._lane(keyword)
        subject = self._title_subject(keyword)
        if lane == "medication":
            return [
                f"{subject} Can Help The Right Person But It Is Not The Whole Strategy",
                "The First Month Is Not The Real Test",
                "The Side Effect And Access Friction People Underestimate",
                "A Composite Scenario That Shows Where The Plan Gets Messy",
                f"{subject} Compared With The Choice People Usually Have In Mind",
                "What To Do Before You Choose This Path",
            ]
        if lane == "cbd":
            return [
                f"{subject} May Help Some People But The Promise Gets Overstated Fast",
                "The Effect You Want And The Effect You Actually Notice Can Be Different",
                "The Product Quality Problem Most Buyers Miss",
                "A Composite Scenario That Shows The Tradeoff Clearly",
                f"{subject} Compared With The Other Options People Usually Try",
                "What To Do Before You Make It A Routine",
            ]
        if lane == "blood":
            return [
                f"{subject} Needs A Pattern Not A Panic Reaction",
                "The Clues That Matter More Than The Number Alone",
                "Where People Misread The Signal First",
                "A Composite Scenario That Shows Why Tracking Changes The Answer",
                f"{subject} Compared With The Checks People Usually Skip",
                "What To Do Before You Guess At The Cause",
            ]
        return [
            f"{subject} Can Work In One Situation And Fail In Another",
            "The First Result Is Not The Real Test",
            "The Friction Most People Notice Too Late",
            "A Composite Scenario That Shows The Turning Point",
            f"{subject} Compared With The Easier Looking Alternative",
            "What To Do Before You Commit",
        ]

    def _opening_story(self, keyword: str) -> str:
        lane = self._lane(keyword)
        subject = self._subject(keyword)
        if lane == "medication":
            return f"I would not judge {subject} by the best success story online. I would judge it by the moment the plan stops feeling new and starts colliding with side effects, refills, cost, follow-up, and daily routine."
        if lane == "cbd":
            return f"I would not judge {subject} by the calmest review on the product page. I would judge it by what happens the next morning, how consistent the product is, and whether the tradeoff still makes sense after the novelty wears off."
        if lane == "blood":
            return f"I would not judge {subject} from one scary number or one vague symptom. I would judge it by the pattern around it, what repeats, and what changes when you track it carefully."
        return f"I would not judge {subject} by the cleanest promise. I would judge it by what happens when the first burst of motivation wears off."

    def _author_bio(self, keyword: str) -> str:
        lane = self._lane(keyword)
        if lane == "cbd":
            return "Evidence-Aware Wellness Editor"
        if lane == "blood":
            return "Evidence-Aware Health Editor"
        return "Evidence-Aware Wellness Editor"

    def _build_locked_viral_body(self, keyword: str) -> str:
        lane = self._lane(keyword)
        sections = self._viral_headings(keyword)
        toc = ["## Table of Contents"] + [f"- [{heading}](#{self._slugify(heading)})" for heading in sections]
        toc += ["- [Frequently Asked Questions](#frequently-asked-questions)", "- [The Next Step Without Guesswork](#the-next-step-without-guesswork)"]
        parts = [
            "> **Disclaimer:** This content is for general educational purposes only and does not replace individualized professional advice.",
            f"Last updated: {datetime.now().strftime('%A, %B %d, %Y')}",
            "\n".join(toc),
            self._direct_opening(keyword),
            self._section_one(keyword, sections[0]),
            self._section_two(keyword, sections[1]),
            self._section_three(keyword, sections[2]),
            self._case_section(keyword, sections[3]),
            self._comparison_section(keyword, sections[4]),
            self._action_guide(keyword, sections[5]),
            self._faq(keyword),
            self._closing(keyword),
            self._tail(keyword),
        ]
        body = "\n\n".join(part.strip() for part in parts if part and part.strip())
        return self._final_cleanup(body, lane)

    def _direct_opening(self, keyword: str) -> str:
        lane = self._lane(keyword)
        subject = self._subject(keyword)
        story = self._opening_story(keyword)
        if lane == "medication":
            answer = (
                f"The short answer is this: {subject} may be worth discussing for the right person, but it is not a shortcut you can judge by results alone. "
                "The real decision is whether the medical fit, side-effect tolerance, prescription access, refill reliability, cost, and maintenance plan are strong enough to hold up after the first month."
            )
        elif lane == "cbd":
            answer = (
                f"The short answer is this: {subject} may feel useful for some people, but the decision gets weaker if the product is inconsistent, the dose is unclear, the next-day effect is annoying, or there are medication interactions you have not checked."
            )
        elif lane == "blood":
            answer = (
                f"The short answer is this: {subject} becomes useful only when you look at the pattern, not the isolated moment. Timing, repeat triggers, other symptoms, meals, stress, sleep, and medical history all change what the signal may mean."
            )
        else:
            answer = (
                f"The short answer is this: {subject} can look promising in the easy version, but the real answer depends on fit, friction, consistency, and what happens after the first result slows down."
            )
        return f"{story}\n\n{answer}"

    def _section_one(self, keyword: str, heading: str) -> str:
        lane = self._lane(keyword)
        subject = self._subject(keyword)
        if lane == "medication":
            body = (
                f"{subject} can look compelling because it gives people a concrete tool instead of another vague instruction to try harder. That matters for readers who have already changed food, movement, sleep, or routine and still feel stuck. But a medication-related decision has to be judged differently from a wellness trend. The right question is not just whether it can help weight move. The right question is whether it fits the person's medical situation and can be managed safely over time.\n\n"
                "That is where many search results become too shallow. They talk about the best-case outcome and skip the boring parts that decide whether the plan survives: follow-up appointments, dose tolerance, refills, lab checks when needed, insurance rules, budget, and what happens if progress slows. A strong article should help the reader prepare better questions for a clinician, not turn a headline into a private treatment plan.\n\n"
                f"[IMAGE: {keyword} real decision]"
            )
        elif lane == "cbd":
            body = (
                f"{subject} can sound appealing because the promise is simple: take something easy, feel calmer, sleep better, or take the edge off discomfort. The problem is that the real experience is usually more conditional. Product quality varies, the amount of CBD can be unclear, some products include other cannabinoids, and people often judge the first night before they understand the pattern.\n\n"
                "The better question is whether the effect is noticeable enough, repeatable enough, and safe enough to justify making it part of a routine. That means looking at next-day grogginess, medication interactions, timing, cost, and whether the product has transparent testing. The hype version makes CBD sound effortless. The useful version asks what actually changes when you track it.\n\n"
                f"[IMAGE: {keyword} real decision]"
            )
        elif lane == "blood":
            body = (
                f"{subject} can feel alarming because blood-related terms sound serious, but one reading or vague symptom rarely tells the whole story. The useful answer starts with pattern recognition. When does it happen? What happened before it? What else changed? Is the pattern repeating, worsening, or appearing with other signs?\n\n"
                "That does not mean ignoring the signal. It means organizing it well enough to make the next step smarter. A clinician can interpret context that a search result cannot, but the reader can still do something useful first: track timing, meals, symptoms, medications, stress, sleep, and repeat readings when appropriate. The pattern often matters more than the panic.\n\n"
                f"[IMAGE: {keyword} tracking pattern]"
            )
        else:
            body = (
                f"{subject} can work in one situation and fail in another because the promise is usually cleaner than the process. The first result is easy to overread. What matters more is whether the plan still makes sense when time, money, routine, appetite, stress, and patience start putting pressure on it.\n\n"
                "That is why this article stays focused on real-life fit. A useful answer should make the decision clearer, not just repeat the claim louder.\n\n"
                f"[IMAGE: {keyword} real process]"
            )
        return f"## {heading}\n\n{body}"

    def _section_two(self, keyword: str, heading: str) -> str:
        lane = self._lane(keyword)
        subject = self._subject(keyword)
        if lane == "medication":
            body = (
                "The first month can be misleading because the decision still feels fresh. People pay closer attention, tolerate inconvenience more easily, and often interpret any early change as proof that the entire plan is working. That early signal matters, but it is not the real test.\n\n"
                f"The real test with {subject} starts when the routine becomes ordinary. Can the person tolerate the side effects during a normal workweek? Can they refill it without stress? Can they afford it if coverage changes? Do they know what to do if progress slows? Do they have food, protein, movement, and follow-up habits that protect the result? Those questions are less exciting than a headline, but they are usually where the decision becomes honest."
            )
        elif lane == "cbd":
            body = (
                "The first night can be misleading because expectation does a lot of work. If someone is tired enough, changes their bedtime, avoids alcohol, and pays closer attention, they may credit the product for a result that came from the whole setup. That does not mean CBD did nothing. It means the effect needs to be tracked with more discipline.\n\n"
                f"A better way to judge {subject} is to watch what happens across several ordinary nights. Is sleep easier, or only different? Do you wake up clearer, or slightly heavy? Does the same product feel consistent? Are you using it alongside medications, alcohol, or other supplements that change the risk? The useful answer lives in that pattern, not in one calm review."
            )
        elif lane == "blood":
            body = (
                "The clues that matter most are usually the ones people forget to write down. Timing matters. Meals matter. Hydration, sleep, stress, illness, exercise, medications, and repeated readings all change the picture. A single number without context is easy to misread.\n\n"
                f"For {subject}, the practical move is to turn a vague worry into a cleaner record. That record does not diagnose you, but it helps you have a better conversation if the pattern keeps repeating. It also helps you avoid two common mistakes: panicking over one isolated moment or normalizing a pattern that deserves attention."
            )
        else:
            body = (
                "The first result is not the real test because motivation is doing some of the work. Most people can follow a clean plan for a short stretch when the idea is new. The harder question is what happens when the plan becomes boring, inconvenient, expensive, or slower than expected.\n\n"
                f"With {subject}, the promise only matters if the system is repeatable. A plan that works only during a perfect week is not the same as a plan that survives travel, stress, meals out, fatigue, and ordinary inconsistency."
            )
        return f"## {heading}\n\n{body}"

    def _section_three(self, keyword: str, heading: str) -> str:
        lane = self._lane(keyword)
        subject = self._subject(keyword)
        if lane == "medication":
            body = (
                f"The friction people underestimate with {subject} is not one single problem. It is the stack. One person may handle the side effects but get blocked by cost. Another may have coverage but struggle with refills. Someone else may tolerate the medication physically but realize they have no maintenance plan once appetite or routine changes.\n\n"
                "That stack is why a medication decision should be handled with a qualified clinician. The useful questions are practical: what side effects should be expected, what warning signs matter, what follow-up is needed, what other medications or conditions change the decision, what happens if access is interrupted, and how the plan will be supported with food, activity, sleep, and long-term habits.\n\n"
                f"[YOUTUBE_VIDEO: {keyword} real-world decision side effects cost]"
            )
        elif lane == "cbd":
            body = (
                f"The friction people underestimate with {subject} is product quality. Two products can look similar on the shelf and behave differently because the CBD amount, cannabinoid profile, testing standards, and added ingredients are not always equal. The label can feel reassuring without answering the questions that matter most.\n\n"
                "The second friction is safety context. CBD can interact with some medications and may not be appropriate for every situation. It can also create next-day grogginess or a result that feels helpful at night but less helpful in the morning. That is why the useful decision is not simply whether CBD sounds natural. It is whether the specific product, dose, timing, and personal context make sense.\n\n"
                f"[YOUTUBE_VIDEO: {keyword} safety effects product quality]"
            )
        elif lane == "blood":
            body = (
                f"The first place people misread {subject} is treating it as either nothing or an emergency without enough context. A better middle path is to look for repetition and clustering. Does it happen after similar meals? At similar times? Alongside fatigue, thirst, dizziness, chest discomfort, headache, numbness, or other changes? Is it new, stronger, or harder to explain?\n\n"
                "That kind of tracking gives you better judgment. It does not replace care, and it should not delay urgent help if symptoms are severe. But for non-emergency uncertainty, a careful pattern can turn a messy search into a useful next conversation with a professional.\n\n"
                f"[YOUTUBE_VIDEO: {keyword} symptoms tracking pattern]"
            )
        else:
            body = (
                f"The friction people notice too late with {subject} is usually not the obvious part. It is the routine pressure: cost, prep time, social inconvenience, symptoms, boredom, or the emotional weight of needing the plan to work.\n\n"
                "When friction stays invisible, people blame themselves. When they name it early, they can decide whether the plan is actually realistic.\n\n"
                f"[YOUTUBE_VIDEO: {keyword} real results tradeoffs]"
            )
        return f"## {heading}\n\n{body}"

    def _case_section(self, keyword: str, heading: str) -> str:
        lane = self._lane(keyword)
        subject = self._subject(keyword)
        if lane == "medication":
            body = (
                f"A realistic composite scenario looks like this. Someone asks about {subject} after months of feeling stuck and starts the conversation with a clinician. The first few weeks feel promising because there is finally a concrete plan. Then the second month gets messy. The stomach symptoms are not dramatic, but they are annoying enough to affect meetings and meals. A refill takes longer than expected. The person starts wondering whether the plan is working or whether the routine is becoming too much work.\n\n"
                "That is the turning point most search results skip. The decision changes from `can this help?` to `can I live with the full process?` The lesson is not that the medication is good or bad for everyone. The lesson is that the result, the side effects, the access path, and the maintenance habits all belong in the same decision."
            )
        elif lane == "cbd":
            body = (
                f"A realistic composite scenario looks like this. Someone buys {subject} because sleep has been inconsistent and the reviews sound calm. The first night feels better, but the next morning is a little heavy. By the end of the week, the pattern is mixed: two nights feel easier, one night feels unchanged, and one morning feels groggier than expected.\n\n"
                "That is the turning point. The question is no longer whether CBD can feel relaxing. The question is whether the specific product, timing, amount, and next-day effect are worth repeating. The useful lesson is to track the whole pattern, not just the best night."
            )
        elif lane == "blood":
            body = (
                f"A realistic composite scenario looks like this. Someone notices {subject} and searches immediately because the phrase sounds serious. At first, they only remember the scary moment. After tracking for two weeks, the pattern becomes clearer: the issue appears after similar meals, on short-sleep days, or alongside another symptom they had not connected before.\n\n"
                "That changes the conversation. Instead of arriving with a vague fear, the person can discuss a pattern: when it happens, how often it repeats, what else shows up, and what seems to make it better or worse. The lesson is not to self-diagnose. It is to make the next professional conversation more useful."
            )
        else:
            body = (
                f"A realistic composite scenario looks like this. Someone starts {subject} with high motivation and sees an early signal that feels encouraging. Then ordinary life returns. Work gets busy, meals become less predictable, and the plan starts requiring more attention than expected.\n\n"
                "That is the turning point. The question changes from whether the idea can work under ideal conditions to whether it can survive normal life."
            )
        return f"## {heading}\n\n{body}"

    def _comparison_section(self, keyword: str, heading: str) -> str:
        lane = self._lane(keyword)
        subject = self._subject(keyword)
        intro = (
            f"A useful comparison for {subject} should be written in reader language, not report language. The point is not to crown a universal winner. The point is to show which tradeoff becomes most important once real life gets involved."
        )
        if lane == "medication":
            table = """| What You Actually Care About | This Option | The Alternative People Usually Compare It With |
|---|---|---|
| How fast it feels | May feel gradual or conditional depending on fit and tolerance | May feel stronger early but can bring more access or cost friction |
| Daily burden | Prescription routine, side effects, refills, and follow-up | Different routine burden such as injections, coverage rules, or stronger appetite changes |
| Biggest disappointment | Expecting the medication to carry the whole strategy | Expecting a more powerful option to be easier to live with |
| Best-fit discussion | Medical history, side effects, cost, and maintenance habits | Appetite pressure, coverage, safety profile, and long-term access |
| What to ask next | What would make this inappropriate or hard to continue | What happens if cost, side effects, or access interrupt the plan |"""
        elif lane == "cbd":
            table = """| What You Actually Care About | CBD Option | Non-CBD Habit Or Product |
|---|---|---|
| How quickly it feels noticeable | Can be subtle and inconsistent | May be more predictable if the issue is routine-based |
| Next-day effect | Possible grogginess or unclear carryover | Usually easier to isolate and adjust |
| Product confidence | Depends on testing, label clarity, and ingredients | Depends on habit consistency or product type |
| Safety context | Interaction and quality questions matter | Different risks depending on the alternative |
| Biggest mistake | Judging by one calm night | Ignoring the root sleep, stress, or pain pattern |"""
        elif lane == "blood":
            table = """| What You Track | Why It Matters | What To Bring Up If It Repeats |
|---|---|---|
| Timing | A pattern after meals, sleep loss, stress, or exercise is more useful than a vague memory | When it happens and how often |
| Other symptoms | Clusters can change the level of concern | Fatigue, thirst, dizziness, pain, numbness, headache, or unusual changes |
| Repeat readings | One number can mislead; repeated patterns are clearer | Whether the pattern is stable, rising, falling, or unpredictable |
| Medication or diet changes | New routines can affect blood-related markers | Recent changes in food, supplements, prescriptions, or illness |
| Urgency signs | Some symptoms should not wait for more tracking | Severe, sudden, or worsening symptoms |"""
        else:
            table = """| What You Actually Care About | The Promising Version | The Real-Life Test |
|---|---|---|
| Early result | Feels motivating | Can fade when novelty wears off |
| Effort | Looks simple from the outside | Requires consistency under stress |
| Cost | Easy to ignore at first | Matters when the plan becomes routine |
| Fit | Sounds good generally | Has to match your actual life |
| Maintenance | Rarely discussed in the headline | Decides whether the result survives |"""
        return f"## {heading}\n\n{intro}\n\n{table}"

    def _action_guide(self, keyword: str, heading: str) -> str:
        lane = self._lane(keyword)
        subject = self._subject(keyword)
        if lane == "medication":
            steps = (
                f"A useful next step for {subject} is not to chase the strongest claim. It is to turn the decision into questions you can take to a qualified clinician.\n\n"
                "1. **Check personal fit first.** Write down your medical history, current medications, previous side effects, and the reason you are considering this option.\n"
                "2. **Check the access path.** Confirm prescription requirements, follow-up schedule, refill reliability, insurance coverage, prior authorization, and realistic monthly cost.\n"
                "3. **Plan for tolerability.** Ask what side effects should be expected, what warning signs deserve attention, and what to do if the dose or routine feels hard to tolerate.\n"
                "4. **Build the maintenance layer.** Discuss protein intake, strength training, sleep, long-term eating patterns, and what happens if the medication is paused or stopped."
            )
        elif lane == "cbd":
            steps = (
                f"A useful next step for {subject} is to treat it like a test, not a personality change.\n\n"
                "1. **Check the product first.** Look for clear labeling, third-party testing, cannabinoid content, and added ingredients.\n"
                "2. **Check interaction risk.** If you take medications, have liver concerns, are pregnant, or have a medical condition, discuss CBD with a qualified professional before making it routine.\n"
                "3. **Track the whole next day.** Do not judge only the night you used it. Track sleep quality, grogginess, mood, and whether the same effect repeats.\n"
                "4. **Compare it against routine fixes.** Timing, caffeine, alcohol, screen use, pain management, and stress may explain more than the product does."
            )
        elif lane == "blood":
            steps = (
                f"A useful next step for {subject} is to stop guessing and make the pattern easier to review.\n\n"
                "1. **Write down timing.** Note when it happens, what you ate or did before it, and whether sleep, stress, exercise, or illness changed.\n"
                "2. **Track what repeats.** One isolated moment matters less than a pattern that keeps showing up or getting stronger.\n"
                "3. **Watch for other signs.** Fatigue, thirst, dizziness, pain, numbness, headaches, or sudden changes can alter the level of concern.\n"
                "4. **Escalate appropriately.** Bring repeat patterns to a qualified professional, and seek urgent care for severe, sudden, or worsening symptoms."
            )
        else:
            steps = (
                f"A useful next step for {subject} is to turn the promise into a decision you can actually test.\n\n"
                "1. **Define the real outcome.** Decide what would count as success beyond one good day.\n"
                "2. **Name the friction.** Track cost, time, symptoms, boredom, and routine pressure.\n"
                "3. **Compare the tradeoff.** Ask whether the payoff is worth what the plan asks from your life.\n"
                "4. **Set a review point.** Decide when you will keep, adjust, or stop the plan instead of drifting."
            )
        return f"## {heading}\n\n{steps}"

    def _faq(self, keyword: str) -> str:
        lane = self._lane(keyword)
        subject = self._subject(keyword)
        if lane == "medication":
            qas = [
                (f"Does {subject} actually work for weight loss if you are not the perfect candidate", f"It may help some people, but the important part is the phrase `some people`. A medication-related weight-loss decision depends on medical history, metabolic context, side-effect tolerance, other prescriptions, cost, and follow-up. If a person expects the medication to replace the whole strategy, disappointment becomes more likely. A better way to frame the question is whether {subject} fits the person's actual health situation and whether a clinician agrees that the potential benefit is worth the tradeoff. Weight change alone is not enough to judge the decision. The plan also has to be safe, affordable, tolerable, and realistic to maintain."),
                (f"Why do people stop seeing progress with {subject}", "Progress can slow for several reasons, and a search result cannot diagnose which one applies. Sometimes early changes are partly motivation, water shifts, or tighter routine. Sometimes side effects make consistency harder. Sometimes food quality, protein intake, sleep, stress, strength training, or medical context become the limiting factor. The practical move is not to panic over a slower trend. It is to bring a clear record to a qualified clinician: what changed, what side effects showed up, what the routine looks like, and whether other health markers need review."),
                (f"Is {subject} worth it if insurance or refills are annoying", "Access friction can change the whole decision. A plan that looks good medically may become stressful if refills are unpredictable, coverage is unclear, or out-of-pocket cost is too high. That does not automatically mean the option is wrong, but it means access belongs in the decision from the start. Ask about realistic monthly cost, prior authorization, refill timing, pharmacy availability, and what to do if a refill is delayed. If the plan depends on perfect access and perfect follow-through, it may not be as durable as the headline makes it sound."),
                (f"What should I ask a clinician before using {subject}", "Ask practical questions, not only outcome questions. Start with whether your medical history, current medications, and goals make the option appropriate to discuss. Then ask what side effects are common, which symptoms should not be ignored, what follow-up is needed, how refills work, and what the maintenance plan should include. It is also worth asking what would make the plan a bad fit. A careful clinician conversation should leave you with a clearer decision, not just a stronger desire for a quick result."),
            ]
        elif lane == "cbd":
            qas = [
                (f"Does {subject} actually work or is it mostly hype", f"It can feel useful for some people, but the honest answer depends on what you are measuring. A calmer night, less tension, or easier sleep onset is not the same as a guaranteed effect. Product quality, timing, dose consistency, added ingredients, expectations, and other routines can all change the result. The best way to judge {subject} is to track the whole pattern: what happened that night, how you felt the next morning, whether the result repeated, and whether any side effects or interactions made the tradeoff less appealing."),
                (f"Can {subject} make you groggy the next morning", "It can for some people, especially when timing, amount, other ingredients, alcohol, or other sleep aids are involved. That is why judging only the night itself can be misleading. A product may seem helpful if you fall asleep faster, but less helpful if the next morning feels dull or heavy. Track alertness, mood, and focus the next day before deciding whether the product is worth repeating. If you take medications or have a medical condition, check with a qualified professional before making CBD part of a routine."),
                (f"How do you know if a CBD product is low quality", "A low-quality product often gives you very little to verify. Watch for vague labels, no third-party testing, unclear CBD amount, confusing cannabinoid claims, aggressive promises, or ingredient lists that hide the real reason the product feels strong. Better product evaluation starts with transparency. You want to know what is in it, how much is in it, whether it has been tested, and whether the company is making claims that sound too medical or too certain."),
                (f"Should you use {subject} every night", "That depends on why you are using it, how you feel the next day, whether the effect repeats, and whether there are safety concerns such as medication interactions. Using it nightly without tracking can hide the real issue, especially if sleep timing, caffeine, alcohol, anxiety, pain, or screen habits are the bigger drivers. A better approach is to treat it like a structured test and review whether it actually improves the problem you care about."),
            ]
        elif lane == "blood":
            qas = [
                (f"When should {subject} worry me", f"A repeating, worsening, severe, sudden, or hard-to-explain pattern deserves more attention than a one-off moment. The context matters: timing, meals, sleep, stress, medications, other symptoms, and whether the issue keeps coming back. If symptoms are severe, sudden, or feel urgent, do not wait for more tracking. For non-emergency uncertainty, write down the pattern and discuss it with a qualified professional so the conversation is based on more than memory."),
                (f"Can {subject} happen even if I feel fine", "Yes, some blood-related patterns can be quiet or easy to miss, which is why symptoms alone are not always enough. That does not mean every small change is dangerous. It means the pattern matters. Repeated readings, timing, other health conditions, medications, family history, and lifestyle context can all change what the result means. If you are unsure, bring clear notes or readings to a professional instead of trying to interpret the pattern from a single search result."),
                (f"What should I track with {subject}", "Track the details that help someone interpret the pattern: time of day, meals, activity, sleep, stress, medications, symptoms, and whether the issue repeats. If numbers are involved, record the actual reading and when it was taken. If symptoms are involved, write down what else happened around the same time. The goal is not to self-diagnose. The goal is to make the next step clearer and reduce the chance of either overreacting or ignoring something that is repeating."),
                (f"Can food or stress affect {subject}", "Food, stress, sleep, illness, activity, hydration, and medication changes can all affect blood-related patterns, depending on the issue. That is why context is so important. A number or symptom that appears after a specific meal, a poor night of sleep, or a stressful day may mean something different from a pattern that appears randomly or keeps worsening. Track the surrounding details and discuss repeat patterns with a qualified professional."),
            ]
        else:
            qas = [
                (f"Does {subject} actually work in real life", f"It can, but only if the real-life version matches the promise. A plan that works during a perfect week may fail when stress, travel, boredom, meals out, cost, or symptoms show up. The better standard is not whether {subject} sounds good. It is whether the result is repeatable when life gets normal again."),
                (f"Why do people get disappointed with {subject}", "Disappointment usually appears when the expectation is cleaner than the process. People expect a shortcut, then discover the routine has tradeoffs. Sometimes the idea still has value, but it cannot carry the whole outcome by itself. The smarter move is to identify the friction early instead of blaming yourself later."),
                (f"How long should you test {subject}", "Long enough to see a pattern, not just one good or bad day. A useful test includes ordinary days, stressful days, and days when motivation is lower. If it only works when everything is perfect, that tells you something important about the plan."),
                (f"What is the biggest mistake with {subject}", "The biggest mistake is treating the promise as the strategy. A real strategy includes what you will do when the plan becomes boring, inconvenient, expensive, or slower than expected. That is where the honest decision usually begins."),
            ]
        lines = ["## Frequently Asked Questions"]
        for question, answer in qas:
            lines.append(f"### {question}\n\n{answer}")
        return "\n\n".join(lines)

    def _closing(self, keyword: str) -> str:
        lane = self._lane(keyword)
        subject = self._subject(keyword)
        if lane == "medication":
            text = f"The useful move after searching {subject} is not to crown a winner from a headline. It is to collect the practical facts that decide whether the option is realistic for you: medical fit, side-effect tolerance, access, coverage, follow-up, cost, and maintenance. Bring those questions to a qualified clinician before turning a search result into a personal plan."
        elif lane == "cbd":
            text = f"The useful move after searching {subject} is not to buy the calmest promise. It is to check product quality, safety context, timing, next-day effect, and whether the result repeats enough to justify the routine."
        elif lane == "blood":
            text = f"The useful move after searching {subject} is not to guess from one moment. It is to track the pattern clearly, watch for repeat or worsening signs, and bring the right context to a qualified professional."
        else:
            text = f"The useful move after searching {subject} is not to copy the loudest claim. It is to test the promise against your actual life and decide whether the tradeoff still makes sense."
        return f"## The Next Step Without Guesswork\n\n{text}"

    def _tail(self, keyword: str) -> str:
        lane = self._lane(keyword)
        if lane == "cbd":
            refs = (
                "- [FDA Cannabis and Cannabis-Derived Products](https://www.fda.gov/news-events/public-health-focus/fda-regulation-cannabis-and-cannabis-derived-products-including-cannabidiol-cbd)\n"
                "- [NCCIH Cannabis and Cannabinoids](https://www.nccih.nih.gov/health/cannabis-marijuana-and-cannabinoids-what-you-need-to-know)\n"
                "- [MedlinePlus Marijuana](https://medlineplus.gov/marijuana.html)"
            )
        elif lane == "blood":
            refs = (
                "- [CDC Diabetes](https://www.cdc.gov/diabetes/)\n"
                "- [NHLBI High Blood Cholesterol](https://www.nhlbi.nih.gov/health/high-blood-cholesterol)\n"
                "- [MedlinePlus Blood Glucose](https://medlineplus.gov/bloodglucose.html)"
            )
        else:
            refs = (
                "- [NIDDK Health Risks of Overweight and Obesity](https://www.niddk.nih.gov/health-information/weight-management/adult-overweight-obesity/health-risks)\n"
                "- [CDC Healthy Weight](https://www.cdc.gov/healthy-weight-growth/)\n"
                "- [MedlinePlus Weight Control](https://medlineplus.gov/weightcontrol.html)"
            )
        return (
            "## AI Disclosure\n"
            "This article draft was prepared with AI assistance and reviewed through a structured editorial workflow.\n\n"
            "## References\n"
            f"{refs}\n\n"
            "## Author\n"
            f"**{self._author_bio(keyword)}**"
        )

    def _final_cleanup(self, body: str, lane: str) -> str:
        cleaned = body
        cleaned = re.sub(r"\b(Search(?:ing)?\s+[^\.]+ usually means|Here is the short version|In conclusion|Furthermore|It is important to note)\b", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\b(drinking|drink|drank)\s+it\b", "using it", cleaned, flags=re.IGNORECASE)
        if lane == "medication":
            cleaned = re.sub(r"\b(Phase\s+(?:I|II|III|1|2|3)|FDA[-\s]?approved|FDA\s+cleared|clinical pipeline|market availability|biological supremacy|guaranteed)\b", "source-dependent claim", cleaned, flags=re.IGNORECASE)
            cleaned = re.sub(r"\btea|smoothie|ritual drink|sweet coffee\b", "routine", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"[ \t]+\n", "\n", cleaned)
        cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
        return cleaned.strip()


def run_cli() -> int:
    parser = argparse.ArgumentParser(description="Run locked viral article generation")
    parser.add_argument("keyword", help="Input search keyword")
    parser.add_argument("--workspace", default=".", help="Workspace root containing references/prompts")
    parser.add_argument("--output", default=".", help="Output directory for generated markdown")
    parser.add_argument("--category", type=int, default=1, help="Article category_id")
    parser.add_argument("--keyword-id", type=int, default=None, help="Optional CMS keyword_id")
    args = parser.parse_args()

    workspace = Path(args.workspace).expanduser().resolve()
    output = Path(args.output).expanduser().resolve()
    controller = EditorialPipelineController(workspace, output_root=output)
    result: PipelineResult = controller.run_generation(
        args.keyword,
        category_id=args.category,
        keyword_id=args.keyword_id,
    )
    preview_path = render_preview_html(result.markdown_path)
    article = load_article(result.markdown_path)
    print(f"Markdown: {result.markdown_path}")
    print(f"Preview: {preview_path}")
    print(f"Title: {article.get('title')}")
    print(f"Category: {article.get('category_id')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(run_cli())
