#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Reusable title pattern families for large SEO keyword pools."""

from __future__ import annotations

TITLE_PATTERNS: dict[str, list[str]] = {
    "glp1_medication": [
        "{kw}: What Happens After the First 12 Weeks",
        "{kw}: Results, Rebound Risk & What Users Should Track",
        "{kw}: Weight Loss, Side Effects & the Long-Term Tradeoff",
        "{kw}: The Appetite Shift, Side Effects & Maintenance Problem",
        "{kw}: What Changes First and What Gets Hard Later",
        "{kw}: Timeline, Dosage Reality & What To Watch",
        "{kw}: What Moves Fast, What Takes Months & What Can Backfire",
        "{kw}: Results Timeline and the Maintenance Question",
        "{kw}: The Part People Notice First and the Part They Miss",
        "{kw}: What The First Month Does and Does Not Prove",
    ],
    "dosage": [
        "{kw}: The Dose Chart People Misread Most Often",
        "{kw}: Starting Dose, Titration & Where Mistakes Happen",
        "{kw}: What The Numbers Mean Before You Increase",
        "{kw}: Weekly Dose Timeline and the Side Effects To Watch",
        "{kw}: Dose Steps, Unit Confusion & What To Check First",
        "{kw}: How Titration Works and Where Users Get Stuck",
        "{kw}: The Dose Timeline, Mistakes & Tracking Plan",
        "{kw}: What To Know Before Moving Up",
    ],
    "reviews_results": [
        "{kw}: What Users Report After the Hype",
        "{kw}: Results, Complaints & What Actually Holds Up",
        "{kw}: What Reviews Reveal and What They Don’t Prove",
        "{kw}: Real-World Results, Weak Spots & What To Track",
        "{kw}: What Changed, What Failed & What Users Missed",
        "{kw}: Review Patterns, Side Effects & The Real Tradeoff",
        "{kw}: What The Before-and-After Stories Leave Out",
        "{kw}: Results Timeline, Complaints & What To Compare",
    ],
    "reality_check": [
        "{kw}? A {year} Reality Check",
        "{kw}? What Works, What Fails & What To Watch",
        "{kw}? The Useful Answer Is More Complicated",
        "{kw}? What Evidence Shows vs What People Repeat",
        "{kw}? Results, Risks & The Real Tradeoff",
        "{kw}? What Users Get Right and Wrong",
        "{kw}? What Actually Changes and What Stays Hype",
        "{kw}? The Claim, The Catch & The Safer Next Step",
    ],
    "pills_commercial": [
        "{kw}: What Works, What Fails & What To Avoid",
        "{kw}: Ranked by Results, Risk & Real-World Fit",
        "{kw}: Which Ones Hold Up and Which Ones Don’t",
        "{kw}: Evidence, Red Flags & What To Compare First",
        "{kw}: The Options Worth Comparing and the Claims To Skip",
        "{kw}: What To Look For Before You Buy",
        "{kw}: Results, Safety Flags & The Labels To Question",
        "{kw}: The Real Difference Between OTC and Prescription Options",
    ],
    "viral_recipe": [
        "{kw}: What The Trend Claims and What Actually Happens",
        "{kw}: Recipe, Results & The Catch People Miss",
        "{kw}: What Works, What Fails & Why It Went Viral",
        "{kw}: The Viral Claim, The Reality & What To Track",
        "{kw}: What To Expect Before You Try It",
        "{kw}: Why The Trend Took Off and Where It Falls Short",
        "{kw}: The Simple Recipe and the Bigger Problem Behind It",
        "{kw}: Results, Risks & What The Trend Leaves Out",
        "{kw}: What Changed, What Didn’t & What To Stop Believing",
        "{kw}: The Method Logic and What Actually Holds Up",
    ],
    "food_diet": [
        "{kw}: What Actually Helps and What Is Just Filling",
        "{kw}: The Options That Keep You Full Longest",
        "{kw}: What Works for Appetite, Protein & Real Fat Loss",
        "{kw}: How To Use It Without Turning It Into Diet Hype",
        "{kw}: What To Eat, What To Skip & What To Track",
        "{kw}: The Satiety Test and the Mistakes People Make",
        "{kw}: What Helps Weight Loss and What Only Sounds Healthy",
        "{kw}: The Practical Way To Use It for Fat Loss",
    ],
    "cost_access": [
        "{kw}: Coverage, Cost & What To Ask First",
        "{kw}: The Insurance Reality Check",
        "{kw}: What You Need Before Calling Your Doctor",
        "{kw}: Price, Coverage & The Step Most People Miss",
        "{kw}: What Gets Covered, What Gets Denied & Why",
        "{kw}: The Access Checklist Before You Pay",
        "{kw}: Doctor Visit, Coverage Rules & Cost Traps",
        "{kw}: How Access Works and Where People Get Stuck",
    ],
    "comparison": [
        "{kw}: Which Works Better and Where Each One Fails",
        "{kw}: Results, Side Effects & The Tradeoff That Matters",
        "{kw}: Real Differences, Cost Gaps & Who Each Fits",
        "{kw}: What Changes When You Compare Them Head-to-Head",
        "{kw}: The Difference That Actually Changes The Decision",
        "{kw}: Which Fits Better, Which Costs More & What To Watch",
        "{kw}: Benefits, Weak Spots & The Better Question To Ask",
        "{kw}: Side-by-Side Results and the Hidden Tradeoff",
    ],
    "public_fact_check": [
        "{kw}: Timeline, Results & What Is Actually Public",
        "{kw}: What Changed, What Is Hype & What People Miss",
        "{kw}: Public Timeline and the Claims That Need Context",
        "{kw}: Before-and-After Claims, Timeline & What Not To Copy",
        "{kw}: The Public Story, The Gaps & The Claims To Question",
        "{kw}: What Was Said, What Was Seen & What Is Speculation",
        "{kw}: Transformation Timeline and What People Keep Getting Wrong",
        "{kw}: What The Photos Show and What They Don’t Prove",
    ],
    "claim_filter": [
        "{kw}: The Benefits That Matter and the Claims That Don’t",
        "{kw}: What Actually Works, What Falls Short & What To Track",
        "{kw}: Real Benefits, Weak Spots & What To Measure",
        "{kw}: What Moved the Needle and What Stayed Hype",
        "{kw}: The Claim Filter Before You Trust the Trend",
        "{kw}: What Looks Promising and Where It Breaks Down",
        "{kw}: The Signals Worth Tracking and the Claims To Ignore",
        "{kw}: What Helps, What Doesn’t & What To Check First",
    ],
    "general_review": [
        "{kw}: What Works, What Fails & What To Watch",
        "{kw}: The Claims That Matter and the Ones To Ignore",
        "{kw}: Real Results, Weak Spots & What To Track",
        "{kw}: What Actually Changed and What Stayed Hype",
        "{kw}: The Practical Answer Behind the Search",
        "{kw}: What To Compare Before You Decide",
        "{kw}: The Useful Signal and the Marketing Noise",
        "{kw}: What The Search Results Usually Leave Out",
    ],
}

FAMILY_PRIORITY: dict[str, list[str]] = {
    "glp1_medication": ["glp1_medication", "reviews_results", "claim_filter"],
    "dosage": ["dosage", "glp1_medication", "safety"],
    "reviews_results": ["reviews_results", "reality_check", "claim_filter"],
    "does_it_work": ["reality_check", "reviews_results", "claim_filter"],
    "best_top": ["pills_commercial", "comparison", "claim_filter"],
    "safety": ["safety", "claim_filter", "reality_check"],
    "viral_recipe": ["viral_recipe", "reality_check", "claim_filter"],
    "pills_commercial": ["pills_commercial", "safety", "comparison"],
    "food_diet": ["food_diet", "claim_filter", "reality_check"],
    "cost_access": ["cost_access", "glp1_medication", "reality_check"],
    "comparison": ["comparison", "claim_filter", "reviews_results"],
    "public_figure": ["public_fact_check", "claim_filter", "reality_check"],
    "benefits": ["claim_filter", "reality_check", "reviews_results"],
    "general_review": ["general_review", "claim_filter", "reality_check"],
}

BANNED_TITLE_PHRASES = [
    "clinical evidence",
    "evidence review",
    "clinical realities",
    "metabolic impacts",
    "long-term expectations",
    "what to expect",
    "comprehensive",
    "ultimate guide",
    "complete guide",
    "deep dive",
    "everything you need to know",
]

HOOK_TOKENS = [
    "works", "fails", "hype", "reality", "tested", "tracked", "results", "risks",
    "side effects", "timeline", "tradeoff", "what to track", "what to avoid",
    "what users", "what changed", "what happens", "what actually",
]
