#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Reusable title pattern families for large SEO keyword pools."""

from __future__ import annotations

TITLE_PATTERNS: dict[str, list[str]] = {
    "glp1_medication": [
        "{kw}: What Happens After the First 12 Weeks",
        "{kw}: Results, Rebound Risk & What Users Should Track",
        "{kw}: Weight Loss, Side Effects & the Long-Term Tradeoff",
        "{kw}: The Appetite Shift, Side Effects & Maintenance Problem",
        "{kw}: What Changes First and What Gets Hard Later",
        "{kw}: Timeline, Dose Reality & What To Watch",
        "{kw}: What Moves Fast, What Takes Months & What Can Backfire",
        "{kw}: Results Timeline and the Maintenance Question",
        "{kw}: The Part People Notice First and the Part They Miss",
        "{kw}: What The First Month Does and Does Not Prove",
        "{kw}: Appetite, Weight Loss & the Plateau Problem",
        "{kw}: What To Track Before The Dose Goes Up",
    ],
    "dosage": [
        "{kw}: The Dose Chart People Misread Most Often",
        "{kw}: Starting Dose, Titration & Where Mistakes Happen",
        "{kw}: What The Numbers Mean Before You Increase",
        "{kw}: Weekly Dose Timeline and the Side Effects To Watch",
        "{kw}: Dose Steps, Unit Confusion & What To Check First",
        "{kw}: How Titration Works and Where Users Get Stuck",
        "{kw}: The Dose Timeline, Mistakes & Tracking Plan",
        "{kw}: What To Know Before Moving Up",
        "{kw}: Starting Low, Moving Up & What Not To Rush",
        "{kw}: Units, Timing & The Mistake That Changes Results",
    ],
    "reviews_results": [
        "{kw}: What Users Report After the Hype",
        "{kw}: Results, Complaints & What Actually Holds Up",
        "{kw}: What Reviews Reveal and What They Don’t Prove",
        "{kw}: Real-World Results, Weak Spots & What To Track",
        "{kw}: What Changed, What Failed & What Users Missed",
        "{kw}: Review Patterns, Side Effects & The Real Tradeoff",
        "{kw}: What The Before-and-After Stories Leave Out",
        "{kw}: Results Timeline, Complaints & What To Compare",
        "{kw}: User Reports, Red Flags & The Claims To Ignore",
        "{kw}: What Looks Real and What Still Needs Context",
    ],
    "reality_check": [
        "{question}? A {year} Reality Check",
        "{question}? What Works, What Fails & What To Watch",
        "{question}? What Evidence Shows vs What People Repeat",
        "{question}? Results, Risks & The Real Tradeoff",
        "{question}? What Users Get Right and Wrong",
        "{question}? What Actually Changes and What Stays Hype",
        "{question}? The Claim, The Catch & The Safer Next Step",
        "{question}? The Useful Answer Is More Complicated",
        "{question}? What To Track Before You Believe It",
        "{question}? Where The Promise Starts To Break",
    ],
    "safety": [
        "{kw}: Common Side Effects, Red Flags & What To Track",
        "{kw}: What Is Normal, What Is Serious & When To Stop Guessing",
        "{kw}: Safety Signals, Side Effects & What Users Miss",
        "{kw}: Side Effects, Risk Factors & The Safer Next Step",
        "{kw}: What Can Go Wrong and What To Watch First",
        "{kw}: Side Effects Timeline and Warning Signs",
        "{kw}: Safety Reality Check and The Questions To Ask",
        "{kw}: Red Flags, Interactions & What To Track",
        "{kw}: The Side Effects People Underestimate",
        "{kw}: What To Avoid Before Problems Start",
    ],
    "pills_commercial": [
        "{kw}: What Works, What Fails & What To Avoid",
        "{kw}: Ranked by Results, Risk & Real-World Fit",
        "{kw}: Which Ones Hold Up and Which Ones Don’t",
        "{kw}: Evidence, Red Flags & What To Compare First",
        "{kw}: The Options Worth Comparing and the Claims To Skip",
        "{kw}: What To Look For Before You Buy",
        "{kw}: Results, Safety Flags & The Labels To Question",
        "{kw}: The Real Difference Between OTC and Prescription Options",
        "{kw}: What The Labels Promise and What They Leave Out",
        "{kw}: The Buying Filter Before You Trust a Pill",
    ],
    "supplement_commercial": [
        "{kw}: What To Compare Before You Buy",
        "{kw}: Ingredient Claims, Red Flags & What To Track",
        "{kw}: Which Claims Hold Up and Which Ones Don’t",
        "{kw}: What Works, What Fails & Label Traps",
        "{kw}: Quality Signals, Side Effects & The Smarter Pick",
        "{kw}: The Supplement Filter Before You Spend Money",
        "{kw}: Reviews, Ingredients & What To Ignore",
        "{kw}: What The Best Options Have in Common",
    ],
    "viral_recipe": [
        "{kw}: What The Trend Claims and What Actually Happens",
        "{kw}: Recipe, Results & The Catch People Miss",
        "{kw}: What Works, What Fails & Why It Went Viral",
        "{kw}: The Viral Claim, The Reality & What To Track",
        "{kw}: What To Know Before You Try It",
        "{kw}: Why The Trend Took Off and Where It Falls Short",
        "{kw}: The Simple Recipe and the Bigger Problem Behind It",
        "{kw}: Results, Risks & What The Trend Leaves Out",
        "{kw}: What Changed, What Didn’t & What To Stop Believing",
        "{kw}: The Method Logic and What Actually Holds Up",
        "{kw}: The Viral Promise vs The Real Fat-Loss Signal",
        "{kw}: How To Use It Without Falling for the Hype",
    ],
    "high_protein": [
        "{kw}: Protein Targets, Fullness & What Actually Helps",
        "{kw}: What Keeps You Full and What Misses the Point",
        "{kw}: The Satiety Plan That Works Better Than Diet Snacks",
        "{kw}: How To Use Protein Without Overcomplicating Weight Loss",
        "{kw}: Meals, Timing & The Mistake That Kills Results",
        "{kw}: What To Eat, What To Track & What To Skip",
        "{kw}: The Practical Protein Filter for Fat Loss",
        "{kw}: Fullness, Muscle Retention & Real-World Fit",
    ],
    "smoothie_juice": [
        "{kw}: What To Blend, What To Skip & What Actually Fills You Up",
        "{kw}: Recipe Ideas, Sugar Traps & The Satiety Test",
        "{kw}: What Works for Appetite and What Turns Into Dessert",
        "{kw}: The Ingredient Filter Before You Drink It",
        "{kw}: Fiber, Protein & The Mistake Most Recipes Make",
        "{kw}: What Helps Fat Loss and What Only Sounds Healthy",
        "{kw}: The Real Difference Between Filling and Low-Calorie",
        "{kw}: How To Build One That Does Not Backfire",
    ],
    "tea_drink": [
        "{kw}: Caffeine, Catechins & What Actually Changes",
        "{kw}: What Helps, What Is Hype & When To Drink It",
        "{kw}: The Thermogenic Claim and What To Track",
        "{kw}: Results, Side Effects & The Tolerance Problem",
        "{kw}: What The Drink Can and Cannot Do",
        "{kw}: Appetite, Energy & The Mistake People Make",
        "{kw}: How To Use It Without Expecting Magic",
        "{kw}: What Works in the Cup and What Does Not",
    ],
    "herb_spice": [
        "{kw}: Claims, Dosage Hype & What To Track",
        "{kw}: What The Trend Gets Right and What It Exaggerates",
        "{kw}: Benefits, Weak Spots & The Safety Check",
        "{kw}: The Inflammation Claim and The Fat-Loss Reality",
        "{kw}: What Actually Changes and What Stays Hype",
        "{kw}: How To Use It Without Treating It Like a Cure",
        "{kw}: The Claim Filter Before You Add It Daily",
        "{kw}: Side Effects, Timing & What To Watch",
    ],
    "fruit_food": [
        "{kw}: Fiber, Sugar & Satiety Compared",
        "{kw}: What Helps Weight Loss and What Is Just Healthy-Sounding",
        "{kw}: The Portion Test and The Mistake People Make",
        "{kw}: Appetite, Calories & What To Track",
        "{kw}: How To Use It Without Overeating It",
        "{kw}: What Works for Fullness and What Does Not",
        "{kw}: The Real Fat-Loss Fit, Not The Wellness Claim",
        "{kw}: What To Eat, What To Limit & Why It Matters",
    ],
    "milk_dairy": [
        "{kw}: Protein, Calories & The Best Fit for Weight Loss",
        "{kw}: What To Compare Before You Pour It",
        "{kw}: The Calorie Trap and The Protein Advantage",
        "{kw}: Which Options Help Fullness and Which Don’t",
        "{kw}: Sugar, Protein & What To Check First",
        "{kw}: The Practical Choice for Appetite Control",
        "{kw}: What Works in a Diet and What Is Just Branding",
        "{kw}: The Label Check Before You Buy",
    ],
    "oil_fat": [
        "{kw}: Appetite Signals, Calories & The Mistake People Make",
        "{kw}: What Helps, What Adds Calories & What To Track",
        "{kw}: The Fat-Loss Claim and The Calorie Reality",
        "{kw}: How To Use It Without Erasing Your Deficit",
        "{kw}: Benefits, Tradeoffs & The Portion Problem",
        "{kw}: The Signal Worth Tracking Before You Add More",
        "{kw}: What Changed, What Didn’t & What To Measure",
        "{kw}: The Useful Dose vs The Easy-to-Overdo Trap",
    ],
    "probiotic": [
        "{kw}: Gut Claims, Weight-Loss Signals & What To Track",
        "{kw}: Strains, Hype & The Results People Overread",
        "{kw}: What Helps Digestion and What Does Not Prove Fat Loss",
        "{kw}: The Microbiome Claim and The Real-World Filter",
        "{kw}: Benefits, Weak Spots & What To Compare",
        "{kw}: What Users Report and What Still Needs Proof",
        "{kw}: The Label Details That Actually Matter",
        "{kw}: How To Judge Results Without Guessing",
    ],
    "whole_food": [
        "{kw}: What Actually Helps and What Is Just Filling",
        "{kw}: The Options That Keep You Full Longest",
        "{kw}: How To Use It Without Turning It Into Diet Hype",
        "{kw}: What To Eat, What To Skip & What To Track",
        "{kw}: The Satiety Test and the Mistakes People Make",
        "{kw}: What Helps Weight Loss and What Only Sounds Healthy",
        "{kw}: The Practical Way To Use It for Fat Loss",
        "{kw}: Fiber, Calories & The Portion Reality",
    ],
    "cost_access": [
        "{kw}: Coverage, Cost & What To Ask First",
        "{kw}: The Insurance Reality Check",
        "{kw}: What You Need Before Calling Your Doctor",
        "{kw}: Price, Coverage & The Step Most People Miss",
        "{kw}: What Gets Covered, What Gets Denied & Why",
        "{kw}: The Access Checklist Before You Pay",
        "{kw}: Doctor Visit, Coverage Rules & Cost Traps",
        "{kw}: How Access Works and Where People Get Stuck",
        "{kw}: What To Bring Up Before The Prescription",
        "{kw}: Cost Questions, Coverage Rules & The First Call",
    ],
    "comparison": [
        "{kw}: Which Works Better and Where Each One Fails",
        "{kw}: Results, Side Effects & The Tradeoff That Matters",
        "{kw}: Real Differences, Cost Gaps & Who Each Fits",
        "{kw}: What Changes When You Compare Them Head-to-Head",
        "{kw}: The Difference That Actually Changes The Decision",
        "{kw}: Which Fits Better, Which Costs More & What To Watch",
        "{kw}: Benefits, Weak Spots & The Better Question To Ask",
        "{kw}: Side-by-Side Results and the Hidden Tradeoff",
        "{kw}: Where One Wins and Where The Other Falls Short",
        "{kw}: The Practical Difference Behind The Search",
    ],
    "public_fact_check": [
        "{kw}: Timeline, Results & What Is Actually Public",
        "{kw}: What Changed, What Is Hype & What People Miss",
        "{kw}: Public Timeline and the Claims That Need Context",
        "{kw}: Before-and-After Claims, Timeline & What Not To Copy",
        "{kw}: The Public Story, The Gaps & The Claims To Question",
        "{kw}: What Was Said, What Was Seen & What Is Speculation",
        "{kw}: Transformation Timeline and What People Keep Getting Wrong",
        "{kw}: What The Photos Show and What They Don’t Prove",
        "{kw}: The Visible Change and The Missing Context",
        "{kw}: What Is Confirmed and What Is Just Repeated Online",
    ],
    "claim_filter": [
        "{kw}: The Benefits That Matter and the Claims That Don’t",
        "{kw}: What Actually Works, What Falls Short & What To Track",
        "{kw}: Real Benefits, Weak Spots & What To Measure",
        "{kw}: What Moved the Needle and What Stayed Hype",
        "{kw}: The Claim Filter Before You Trust the Trend",
        "{kw}: What Looks Promising and Where It Breaks Down",
        "{kw}: The Signals Worth Tracking and the Claims To Ignore",
        "{kw}: What Helps, What Doesn’t & What To Check First",
        "{kw}: The Useful Signal and The Marketing Noise",
        "{kw}: What To Believe, What To Doubt & What To Track",
    ],
    "ranked_review": [
        "{kw}: Ranked by Results, Risk & Real-World Fit",
        "{kw}: Which Options Hold Up and Which Ones Don’t",
        "{kw}: What To Compare Before You Choose",
        "{kw}: Best Picks, Red Flags & What Actually Matters",
        "{kw}: The Shortlist and The Claims To Question",
        "{kw}: What Works Best and Where Each Option Falls Short",
        "{kw}: A Practical Ranking by Fit, Risk & Results",
        "{kw}: The Options Worth Comparing First",
    ],
    "general_review": [
        "{kw}: What Works, What Fails & What To Watch",
        "{kw}: The Claims That Matter and the Ones To Ignore",
        "{kw}: Real Results, Weak Spots & What To Track",
        "{kw}: What Actually Changed and What Stayed Hype",
        "{kw}: The Practical Answer Behind the Search",
        "{kw}: What To Compare Before You Decide",
        "{kw}: The Useful Signal and the Marketing Noise",
        "{kw}: What The Search Results Usually Leave Out",
    ],
}

FAMILY_PRIORITY: dict[str, list[str]] = {
    "glp1_medication": ["glp1_medication", "reviews_results", "claim_filter"],
    "dosage": ["dosage", "safety", "glp1_medication"],
    "reviews_results": ["reviews_results", "reality_check", "claim_filter"],
    "does_it_work": ["reality_check", "claim_filter", "reviews_results"],
    "best_top": ["ranked_review", "comparison", "claim_filter"],
    "safety": ["safety", "claim_filter", "reality_check"],
    "viral_recipe": ["viral_recipe", "reality_check", "claim_filter"],
    "pills_commercial": ["pills_commercial", "safety", "ranked_review"],
    "supplement_commercial": ["supplement_commercial", "claim_filter", "safety"],
    "high_protein": ["high_protein", "whole_food", "claim_filter"],
    "smoothie_juice": ["smoothie_juice", "viral_recipe", "claim_filter"],
    "tea_drink": ["tea_drink", "claim_filter", "reality_check"],
    "herb_spice": ["herb_spice", "claim_filter", "safety"],
    "fruit_food": ["fruit_food", "whole_food", "claim_filter"],
    "milk_dairy": ["milk_dairy", "whole_food", "claim_filter"],
    "oil_fat": ["oil_fat", "claim_filter", "reality_check"],
    "probiotic": ["probiotic", "claim_filter", "reviews_results"],
    "whole_food": ["whole_food", "claim_filter", "reality_check"],
    "food_diet": ["whole_food", "claim_filter", "reality_check"],
    "cost_access": ["cost_access", "glp1_medication", "reality_check"],
    "comparison": ["comparison", "claim_filter", "reviews_results"],
    "public_figure": ["public_fact_check", "claim_filter", "reality_check"],
    "benefits": ["claim_filter", "reality_check", "reviews_results"],
    "general_review": ["general_review", "claim_filter", "reality_check"],
}

BANNED_TITLE_PHRASES = [
    "clinical evidence",
    "evidence review",
    "clinical realities",
    "metabolic impacts",
    "long-term expectations",
    "what to expect",
    "comprehensive",
    "ultimate guide",
    "complete guide",
    "deep dive",
    "everything you need to know",
]

HOOK_TOKENS = [
    "works", "fails", "hype", "reality", "tested", "tracked", "results", "risks",
    "side effects", "timeline", "tradeoff", "what to track", "what to avoid",
    "what users", "what changed", "what happens", "what actually", "red flags",
    "dose", "coverage", "cost", "claims", "signal", "mistake", "catch",
]
